### ISSUE TITLE
Javier, necesitas documentación javadoc

### ISSUE THREAD

**Issue by gboquizo** [jponferrada26/Practica_Issue_Javier#1]
Javier, necesitar documentar tu proyecto con documentación javadoc, coméntale para que  @jaimerabasco pueda evaluarte:

https://github.com/jponferrada26/Practica_Issue_Javier/blob/master/adivinalo/src/adivinalo/Partida.java#L11-L12

https://github.com/jponferrada26/Practica_Issue_Javier/blob/master/adivinalo/src/adivinalo/Partida.java#L59-L60

https://github.com/jponferrada26/Practica_Issue_Javier/blob/master/adivinalo/src/adivinalo/Partida.java#L65-L66

https://github.com/jponferrada26/Practica_Issue_Javier/blob/master/adivinalo/src/adivinalo/Partida.java#L78-L79

https://github.com/jponferrada26/Practica_Issue_Javier/blob/master/adivinalo/src/adivinalo/Partida.java#L88-L89

https://github.com/jponferrada26/Practica_Issue_Javier/blob/master/adivinalo/src/adivinalo/Partida.java#L93-L94

**Comment by jponferrada26** [comment]
De acuerdo. Lo cambiaré lo antes lo antes posible @gboquizo
